### ISSUE TITLE
Save Game system

### ISSUE THREAD

**Issue by Ashimaru** [Ashimaru/strategy#3]

**Comment by Leoneedus** [comment]
Have to change serialization method for security reasons.
https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide

**Comment by Ashimaru** [comment]
I guess for now its fine

**Comment by Leoneedus** [comment]
Save system core works. Saving specific entities should be done later on when it will be needed. In other case it may cause additional work when refactoring code. 
If you want to save game entity you need to add SaveableEntity component to your object in the scene. Then every script component that data should be saved needs to inherit from ISaveable. 
SaveableEntity will as well add PersistantId component to the gameobject. In order to generate Id user need to invoke context menu on the PersistantId component and click GenerateId option. It needs to be done once per PersistantId component creation.
